LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := cb04_6735_35u

MODULES += app/mt_boot \
           dev/lcm


MTK_EMMC_SUPPORT = yes
MACH_FPGA_LED_SUPPORT = no
ifeq ($(MACH_FPGA_LED_SUPPORT),yes)
DEFINES += MACH_FPGA_LED_SUPPORT
endif
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
#MTK_KERNEL_POWER_OFF_CHARGING=yes
MTK_LCM_PHYSICAL_ROTATION = 0
#CUSTOM_LK_LCM="ota7290b_dsi_ivo nt35521_hd720_dsi_vdo_lide otm1287a_hd720_dsi_vdo_boyi"
#CUSTOM_LK_LCM="icn6202_lcm_drv"
#DEFINES+=CONFIG_ICN6202
#CUSTOM_LK_LCM="ota7290b_dsi_ivo"
CUSTOM_LK_LCM="wtl0988_dsi_ivo"
#hx8392a_dsi_cmd_qhd = yes

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes

DEBUG := 0
#BOOT_LOGO = cu_lte_qhd
BOOT_LOGO = cu_lte_hd720
#BOOT_LOGO = t-roadlvds
#BOOT_LOGO = wsvganl

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
#DEFINES += SB_LK_BRINGUP=y
DEFINES += MTK_GPT_SCHEME_SUPPORT
ifeq ($(TARGET_QRD_BUILD_SPEC),gz_hg)
DEFINES += NO_LOW_BAT_CON
endif
